In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
:$$
in_

In [ ]:
x = np.linspace(-0.6 , 1.4 , 120)
y = 1+np.exp(-x)np.cos(3*x)
y1= y[0:3]
dx = -x[0] + x[3]
fArea = dx*np.sum(y1)
print("integral area :" , fArea)

SyntaxError: ignored

pregunta 1






pregunta 2

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
N = 10000000
a = -10000
b = 10000
x = np.random.uniform(a, b, N)
y = np.exp(x**2)
sumfx = np.sum(y)
farea = ((b-a)/N) * sumfx 
print("El area es: ",farea)


El area es:  inf


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in exp
  """


pregunta 3

In [ ]:
from numpy import array, zeros, diag, diagflat, dot

In [ ]:
def jacobi(A,b,N=20,x=None):                        
    """ AX=B - Jacobi Método Iterativo. """

    if x is None:
        x = zeros(len(A[0]))                                 
    D = diag(A)                                       
    R = A - diagflat(D)                                    

    for i in range(N):
        x = (b - dot(R,x)) / D                                
    return x

In [ ]:
A = array([[3, -1, 2], [-1, +3, 1], [-1, 1, 4]])                     
b = array([1, 3, 7])                                                  
sol = jacobi(A,b,N=3)

In [ ]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[ 3 -1  2]
 [-1  3  1]
 [-1  1  4]]
b:
[1 3 7]
x:
[-0.5462963   0.30555556  1.49305556]
