###PREGUNTA 1
- - - 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

Rectangulos

In [ ]:
x = np.linspace(-0.6,1.4,120)      
y = 1+np.cos(3*x)*np.exp(-x)           
y1 = y[0:-1]
dx = x[1] - x[0]                   
fArea = dx*np.sum(y1)              
print("Integral area:",fArea)

Integral area: 2.4359722102066876


Trapecios

In [ ]:
x = np.linspace(-0.6,1.4,100)        
y = 1+np.cos(3*x)*np.exp(-x)                
y1 = y[1:-1] 
dx = x[1] - x[0]                
fsum1 = np.sum(2*y1)
fsum = fsum1 + y[0] + y[-1]
fArea = (dx/2)*fsum             
print(fArea)

2.4383831067940376


###PREGUNTA 2
- - - 

Montecarlo

In [ ]:
N = 10000000      
a = -10000             
b = 10000             
x = np.random.uniform(a, b, N)

y = 1/(1+x**2)       

sumfx = np.sum(y)
farea = ((b - a) / N) * sumfx
print("El área es: ", farea)

El área es:  3.116105360629955


###PREGUNTA 3
- - - 

In [ ]:
from numpy import array, zeros, diag, diagflat, dot

In [ ]:
def jacobi(A,b,N=25,x=None):
    """ AX=B - Jacobi Método Iterativo. """
    

    if x is None:
        x = zeros(len(A[0]))

    
    D = diag(A)
    R = A - diagflat(D)

     
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

In [ ]:
A = array([[3, -1, -1], [-1, 3, 1], [2, 1, 4]])    
b = array([1, 3, 7])                                  

sol = jacobi(A,b,N=20)   

In [ ]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[ 3 -1 -1]
 [-1  3  1]
 [ 2  1  4]]
b:
[1 3 7]
x:
[1. 1. 1.]
