###PREGUNTA 1
- - -

In [1]:
import numpy as np
import matplotlib.pyplot as plt

**a)RECTANGULO**

In [23]:
x = np.linspace(-1,0,20)      
y = x*np.sqrt(x**2 + 9)            
y1 = y[0:-1]
dx = x[1] - x[0]                   
fArea1 = (dx*np.sum(y1))*(-1)              
print("Integral area:",fArea1)

Integral area: 1.6242538278414327


In [8]:
x = np.linspace(0,1,20)      
y = x*np.sqrt(x**2 + 9)            
y1 = y[0:-1]
dx = x[1] - x[0]                   
fArea2 = dx*np.sum(y1)              
print("Integral area:",fArea2)

Integral area: 1.4578181615167827


In [21]:
print("El área es:", fArea1 + fArea2 )

El área es: 2.9988541561958915


**b)TRAPECIO**

In [19]:
x = np.linspace(-1,0,20)        
y = x*np.sqrt(x**2 + 9)                
y1 = y[1:-1] 
dx = x[1] - x[0]                
fsum1 = np.sum(2*y1)
fsum = fsum1 + y[0] + y[-1]
fArea1 = ((dx/2)*fsum)*(-1)             
print(fArea1)

1.541035994679107


In [20]:
x = np.linspace(0,1,20)        
y = x*np.sqrt(x**2 + 9)                
y1 = y[1:-1] 
dx = x[1] - x[0]                
fsum1 = np.sum(2*y1)
fsum = fsum1 + y[0] + y[-1]
fArea1 = ((dx/2)*fsum)           
print(fArea1)

1.5410359946791086


In [22]:
print("El área es:", fArea1 + fArea2 )

El área es: 2.9988541561958915


###PREGUNTA 2 MONTECARLO
- - -





In [11]:
N = 84751     
a = 1              
b = np.sqrt(3)          
x = np.random.uniform(a, b, N)

y = 1/(1 + x**2)       

sumfx = np.sum(y)
farea = ((b - a) / N) * sumfx
print("El área es: ", farea)

El área es:  0.2616068829490793


### PREGUNTA 3 JACOBI
- - -

In [13]:
from numpy import array, zeros, diag, diagflat, dot

In [14]:
def jacobi(A,b,N=25,x=None):
    """ AX=B - Jacobi Método Iterativo. """
    # Crear la conjetura (hipótesis, supuesto) inicial
    # Si se necesita
    if x is None:
        x = zeros(len(A[0]))

    # Crear una matriz diagonalizada de A
    D = diag(A)
    R = A - diagflat(D)

    # Iteración por N veces 
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

In [30]:
A = array([[3, -1, 1], [2, 5, -2], [1, -1, -3]])    
b = array([4, -6, 6])                                  

sol = jacobi(A,b,N=21)   

In [31]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[ 3 -1  1]
 [ 2  5 -2]
 [ 1 -1 -3]]
b:
[ 4 -6  6]
x:
[ 1.00001974 -1.99995264 -1.00005921]
