In [ ]:
from numpy import array, zeros, diag, diagflat, dot

### Ejemplo 1 - JACOBI

In [ ]:
A = array([[2.0,1.0],[5.0,7.0]])
b = array([11.0,13.0])
x = array([1.0,1.0])

sol = jacobi(A,b,x=x)

In [ ]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[2. 1.]
 [5. 7.]]
b:
[11. 13.]
x:
[ 7.11110202 -3.22220342]


### Ejemplo 2-A

In [ ]:
def jacobi(A,b,N=25,x=None):
    """ AX=B - Jacobi Método Iterativo. """
    # Crear la conjetura (hipótesis, supuesto) inicial
    # Si se necesita
    if x is None:
        x = zeros(len(A[0]))

    # Crear una matriz diagonalizada de A
    D = diag(A)
    R = A - diagflat(D)

    # Iteración por N veces 
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

In [ ]:
A = array([[.7, .1, -8.2],[25, -.9, -.3], [3.7, -7.3, -.1]])
b = array([-56.4, 20.2, -18.9])

sol = jacobi(A,b,N=3)

In [ ]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[ 0.7  0.1 -8.2]
 [25.  -0.9 -0.3]
 [ 3.7 -7.3 -0.1]]
b:
[-56.4  20.2 -18.9]
x:
[-13263.39002268  59713.09171076 248862.88888889]


### Ejemplo 2-B

In [ ]:
A = array([[25, -.9, -.3], [3.7, -7.3, -.1], [.7, .1, -8.2]])
b = array([20.2, -18.9, -56.4])

sol = jacobi(A,b,N=3)

In [ ]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[25.  -0.9 -0.3]
 [ 3.7 -7.3 -0.1]
 [ 0.7  0.1 -8.2]]
b:
[ 20.2 -18.9 -56.4]
x:
[0.99629997 2.99205285 6.99744573]
