###*** 1 metodo rectangulo***


In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [8]:
x = np.linspace(-1,1,20)                    
y = x*(((x**2) +9)**1/2)      
y1 = y[0:-1]
dx = x[1] - x[0]                            
fArea = dx*np.sum(y1)                        
print("Integral area:",fArea)

Integral area: -0.5263157894736848


###***1 metodo trapecios***


In [16]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
x = np.linspace(-1,1,20)                  
y = x*(((x**2) +9)**1/2)        
y1 = y[1:-1]
dx = x[1] - x[0]                           
fsum1 = np.sum(2*y1)                       
fsum = fsum1 + y[0] + y[-1]                 
fArea = (dx/2)*fsum                        
print("Integral Area:" ,fArea)

Integral Area: -4.674623261579606e-16


###***error***


###***2 monte carlo***


In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
N = 85758                                         
a = 1                                                                 
b = 3**1/2                                              
x = np.random.uniform(a, b, N)                      
                                                    
y =1/(1+x**2)                 

sumfx = np.sum(y)
farea = ((b - a) / N) * sumfx
print("El área es: ", farea)

El área es:  0.19734811761300922


###***3jacobi***

In [26]:
from numpy import array, zeros, diag, diagflat, dot

In [31]:
def jacobi(A,b,N=25,x=None):                                
    """ AX=B - Jacobi Método Iterativo. """
    
  
    if x is None:
        x = zeros(len(A[0]))                                 
    
    D = diag(A)                                            
    R = A - diagflat(D)                                   
                                                        
    
    for i in range(N):
        x = (b - dot(R,x)) / D                              
    return x

In [35]:
A = array([[3, -1, 1], [2, 5, -2], [1, -1, -3]])                    
b = array([4, -6, 6])                                                   
 
sol = jacobi(A,b,N=3)

In [36]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[ 3 -1  1]
 [ 2  5 -2]
 [ 1 -1 -3]]
b:
[ 4 -6  6]
x:
[ 0.87407407 -2.30222222 -0.62222222]
