##2do parcial


In [ ]:
import numpy as np


In [ ]:
#PREGUNTA 1 INCISO A
x = np.linspace(0,1,20)
print(x)
print(type(x))
y = x* np.sqrt(x**2+9)
print(y)
y1 = y[0:-1]
dx = x[1] - x[-1]                        # Ancho de cada rectángulo
print(dx)
fArea = dx*np.sum(y1)                    # Rectángulo ancho * alto, luego suma
print("Integral area:",fArea)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
<class 'numpy.ndarray'>
[0.         0.15791903 0.31598381 0.47433983 0.63313217 0.79250524
 0.95260254 1.11356652 1.2755383  1.43865753 1.60306219 1.7688884
 1.93627026 2.1053397  2.27622635 2.4490574  2.62395747 2.80104853
 2.9804498  3.16227766]
-0.9473684210526316
Integral area: -26.240726907302093


In [ ]:
#PREGUNTA 1 INCISO B
x = np.linspace(0,1,20)
y = x* np.sqrt(x**2+9)
y1 = y[1:-1]
dx = x[1] - x[-1]        # Ancho de cada trapecio
fsum1 = np.sum(2*y1)
fsum = fsum1 + y[0] + y[-1]
fArea = (dx/2)*fsum     # suma de areas del trapecio
print(fArea)

-27.73864790422396


In [ ]:
import scipy.integrate as integrate
import math

In [ ]:
#PREGUNTA 1 INCISO C #NO SE HACE
res = integrate.quad(lambda x: x* np.sqrt(x**2+9), 0, 1)
print("El área es {0}, con un error de {1}".format(res[0], res[1]))

El área es 1.5409255338945977, con un error de 1.7107710069625944e-14


In [ ]:
# PREGUNTA 2 METODO MONTE CARLO
N = 100000
# limite inferior
a = np.sqrt(3)
# limite superior
b = 1
x = np.random.uniform(a, b, N)

y = 1 / 1 + x**2

sumfx = np.sum(y)
farea = ((b - a) / N) * sumfx
print("El área es: ", farea)

El área es:  -2.1265420655952165


In [ ]:
#PREGUNTA 3 SISTEMA DE ECUACIONES
from numpy import array, zeros, diag, diagflat, dot

In [ ]:
def jacobi(A,b,N=25,x=None):
    """ AX=B - Jacobi Método Iterativo. """
    # Crear la conjetura (hipótesis, supuesto) inicial
    # Si se necesita
    if x is None:
        x = zeros(len(A[0]))

    # Crear una matriz diagonalizada de A
    D = diag(A)
    R = A - diagflat(D)

    # Iteración por N veces 
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

In [ ]:
A = array([[3, -1, 1],[2, 5, -2], [1, -1, -3]])
b = array([4, -6, 6])

sol = jacobi(A,b,N=25)

In [ ]:
print("A:")
print(A)
print("b:")
print(b)
print("x:")
print(sol)

A:
[[ 3 -1  1]
 [ 2  5 -2]
 [ 1 -1 -3]]
b:
[ 4 -6  6]
x:
[ 1.00000282 -1.99999324 -1.00000845]
